[app]
host="0.0.0.0"
port=8099

[database]
host="192.168.0.116"
port=3306
user = "root"
password = "12345678"
name = "rust_web"


[log]
level = "info"
path = "app.log"


[kafka_config]
brokers = "192.168.0.116:9092"
group_id = "test_group"

[redis_config]
cluster = "redis://192.168.0.116:6379/"