[app]
host="0.0.0.0"
port=8099

[database]
host="localhost"
port=3306
user = "root"
password = "12345678"
name = "rust_web"


[log]
level = "info"
path = "app.log"


[kafka_config]
brokers = "localhost:9092"
group_id = "test_group"

[redis_config]
cluster = "redis://localhost:6379/"